name: VEditor GitHub Pages
on:
  push:
    branches:
      - dev 
jobs:
  package-and-deploy:
    name: Docs & demo to GitHub Pages
    runs-on: [self-hosted, nebula-fast]
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:all && npm run doc
      - name: Delete node_modules
        run: rm -rf node_modules && rm -rf demo && rm -rf src
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
          keep_files: true
          force_orphan: true